#!/bin/bash

# Making the script more robust
set -e # Exit on errors
set -u # Exit on uninitialized variables

cd test-project
export RAILS_ENV=test
export RAILS_VERSION=3.2.15

# Configure database access
cp -f config/database.yml.example config/database.yml

# Create databases and sharding tables
service mysql restart
mysql -u root < db/create_databases.sql
mysql -u root db_charmer_sandbox_test < db/sharding.sql

# Install gems
rm -f Gemfile.lock
bundle install

# Run migrations
bundle exec rake --trace db:migrate

exec bundle exec rspec -cbfs spec
