source 'http://rubygems.org'

gem 'rake', "0.9.2.2"
gem 'mysql2', "0.3.14"

gem 'rspec', '< 3.0'
gem 'rspec-core', '< 3.0'
gem 'rspec-rails', '< 3.0'
gem 'test-unit'

# Load DbCharmer as a gem
gem_path = File.expand_path(File.dirname(File.dirname(__FILE__)))
puts "Using on-disk db-charmer code from '#{gem_path}'..."
gem 'db-charmer', :path => gem_path, :require => 'db_charmer'

# Require gems for selected rails version
gem "rails", ENV['RAILS_VERSION']
gem 'rails4_upgrade', github: 'alindeman/rails4_upgrade'